---
- name: install fail2ban
  package:
    name: fail2ban
    state: present
  environment: "{{ proxy_env }}"
  become: true
  tags: fail2ban

- name: configuring fail2ban
  template:
    src: "{{ item }}.j2"
    dest: "/etc/fail2ban/{{ item }}"
  notify: "restart fail2ban"
  with_items: '{{ fail2ban_configs }}'
  become: true
  tags: fail2ban

- name: start and enable fail2ban service
  systemd:
    name: fail2ban
    enabled: yes
  become: true
  tags: fail2ban
